name: "CI/CD"
on: 
  push:
    branches:
      - main
    tags:
      - '*'
jobs:
  build:
    name: "Build and publish artifacts"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: "Checkout"

      - uses: actions/setup-node@v2
        name: "Setup Node"
      
      - run: npm install
        name: "Install dependencies"

      - run: npm run build
        name: "Build"
      
      - run: zip -9 -r app.zip .
        name: "Compress" 

      - name: "Upload app artifact"
        uses: actions/upload-artifact@v2
        with:
          name: meeting-break-bot
          path: ./app.zip

  deploy:
    name: "Deploy"
    needs: build
    runs-on: ubuntu-latest
    if: startsWith( github.ref, 'refs/tags/')
    env:
      AZURE_WEBAPP_NAME: msteamsmeetingbreakapi
      AZURE_WEBAPP_PACKAGE_PATH: 'dist/app.zip' 
    steps:
      - uses: actions/checkout@v2
        name: "Checkout"
      
      - name: "Download meeting break bot"
        uses: actions/download-artifact@v2
        id: download
        with:
          name: meeting-break-bot
          path: dist

      - name: 'Deploy to Azure'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}